#!/bin/sh -e

SCRIPT_DIR=$(cd $(dirname "$0") ; pwd -P)
PROJECT_HOME=$(dirname $SCRIPT_DIR)
cd "$PROJECT_HOME"

comment="$1"

if [ -z "$comment" ]
then
	comment="Project updated"
fi

git add -A .
git commit -a -m "$comment"
git push origin
